name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ luizadas }}
          password: ${{ Ncsn3130docker., }}

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and Run Services with Docker Compose
        run: docker-compose up -d --build

      - name: Run Application Tests
        run: |
          # Substitua `app` pelo nome do seu serviço principal no docker-compose.yml
          docker-compose exec app php artisan test

      - name: Tear Down
        if: always()
        run: docker-compose down
